### ISSUE TITLE
Help: Installing Sass with homebrew

### ISSUE THREAD

**Issue by chiweilin830908** [sass/homebrew-sass#26]
I installed homebrew successfully, but when I run `brew install sass/sass/sass`, I always get the screenshot below: 
<img width="676" alt="Screen Shot 2019-12-01 at 9 51 56 PM" src="https://user-images.githubusercontent.com/49460434/69915003-290ac900-1485-11ea-804c-c58b59c21c26.png">

Always failing to install Sass, is there anyone who can help me with this issue? I am so confused.

By the way, I use MacBook pro, and it's v10.14.2

**Comment by jathak** [comment]
It looks like this error is coming from Pub.

First, check that your Dart version (`/usr/local/opt/dart/bin/dart --version`) is at least 2.6.0 (since that's the minimum Dart version the latest Sass requires). If it's not, run `brew update && brew upgrade dart` before trying to install Sass again.

If that doesn't work, you'll likely want to report this as a bug in [Pub](https://github.com/dart-lang/pub/issues/new?template=2-BUG.md)

**Comment by marshalc** [comment]
I'm having this same problem, and had attempted to add to the linked https://github.com/dart-lang/pub/issues/2271#issuecomment-750911453 `dart-lang/pub` thread. However, not being a Dart user/developer, I'm unfamiliar with the setup and don't have access to the SDK tools.

I can confirm that...

```
➜  ~ which dart
/usr/local/bin/dart
➜  ~ dart --version
Dart SDK version: 2.10.4 (stable) (Wed Nov 11 13:35:58 2020 +0100) on "macos_x64"
➜  ~ 
```

... so this doesn't seem to be a minimum version issue. I have also successfully installed this package via homebrew on another Big Sur machine (though differing build orders/history) so I'm wondering if this is a build logic issue?

**Comment by nex3** [comment]
This crash is coming from within Dart's package manager. Can you file an issue against https://github.com/dart-lang/pub?
